version: 1
title: Dremel Bit Storeage
tags:
  - tool accessories
  - bit holder
  - dremel
link: 
  name: Thangs
  url: https://thangs.com/designer/thing3dyer/3d-model/%2523Gridfinity%2520Workbench%2520Dremel%2520Bit%2520storage%2520Remix-63134
author: 
  name: thing3dyer
  url: https://thangs.com/designer/thing3dyer