version: 1
title: Divider Box
link: 
  name: Thangs
  url: https://thangs.com/designer/ZackFreedman/3d-model/Gridfinity%2520Divider%2520Bins-60721
author: 
  name: Zack Freedman
  url: https://thangs.com/designer/ZackFreedman