version: 2
title: Frame Baseplate
tags:
  - general
  - baseplate
link: 
  name: Thangs
  url: https://thangs.com/designer/ZackFreedman/3d-model/Gridfinity%20Baseplates-60925
author: 
  name: Zack Freedman
  url: https://thangs.com/designer/ZackFreedman